// Top-level emit driver for Zig codegen.
const common = @import("common.zig");
const std = common.std;
const lir = common.lir;
const EmitError = common.EmitError;
const hasAccountRecordType = common.hasAccountRecordType;
const paramsNeedEntrypointAccounts = common.paramsNeedEntrypointAccounts;
const append = common.append;
const decl_emission = @import("decl_emission.zig");
const emitVariantType = decl_emission.emitVariantType;
const emitRecordType = decl_emission.emitRecordType;
const emitClosureCaptureStructs = decl_emission.emitClosureCaptureStructs;
const emitFunction = decl_emission.emitFunction;
const emitBuiltinAccountRecordType = decl_emission.emitBuiltinAccountRecordType;
const emitAccountViewHelper = decl_emission.emitAccountViewHelper;

pub fn emitModule(allocator: std.mem.Allocator, module: lir.LModule) EmitError![]const u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);

    try append(&out, allocator,
        \\// Generated by omlz; do not edit
        \\// Zig 0.16 BPF workaround: before generated code takes the address of
        \\// any module-scope const array, it must copy that array to a local
        \\// stack slot and take the stack copy's address. Otherwise LLVM may
        \\// place the array at low addresses (0x0/0x20) rejected by Solana.
        \\const std = @import("std");
        \\const Arena = @import("runtime/arena.zig").Arena;
        \\const AccountRuntime = @import("runtime/account.zig");
        \\const cpi = @import("runtime/cpi.zig");
        \\const prelude = @import("runtime/prelude.zig");
        \\const runtime_panic = @import("runtime/panic.zig");
        \\const spl_token = @import("runtime/spl_token.zig");
        \\const syscalls = @import("runtime/syscalls.zig");
        \\
        \\
    );
    for (module.type_decls) |type_decl| {
        try emitVariantType(&out, allocator, type_decl);
        try append(&out, allocator, "\n");
    }
    const has_account_record = hasAccountRecordType(module.record_type_decls);
    const needs_account_support = has_account_record or paramsNeedEntrypointAccounts(module.entrypoint.params);
    for (module.record_type_decls) |type_decl| {
        try emitRecordType(&out, allocator, type_decl);
        try append(&out, allocator, "\n");
    }
    if (!has_account_record and needs_account_support) {
        try emitBuiltinAccountRecordType(&out, allocator);
        try append(&out, allocator, "\n");
    }
    if (needs_account_support) {
        try emitAccountViewHelper(&out, allocator);
        try append(&out, allocator, "\n");
    }
    try emitClosureCaptureStructs(&out, allocator, module.functions);
    for (module.functions) |func| {
        if (isCounterHelperName(func.name)) continue;
        try emitFunction(&out, allocator, func, module.functions, module.type_decls, module.record_type_decls, module.externals);
        try append(&out, allocator, "\n");
    }
    try emitFunction(&out, allocator, module.entrypoint, module.functions, module.type_decls, module.record_type_decls, module.externals);

    return out.toOwnedSlice(allocator);
}

pub fn isCounterHelperName(name: []const u8) bool {
    return std.mem.eql(u8, name, "read_u8") or
        std.mem.eql(u8, name, "read_u64_le") or
        std.mem.eql(u8, name, "write_u64_le") or
        std.mem.eql(u8, name, "set_account_data") or
        std.mem.eql(u8, name, "transfer_sol") or
        std.mem.eql(u8, name, "vault_deposit") or
        std.mem.eql(u8, name, "vault_withdraw") or
        std.mem.eql(u8, name, "vault_v2_deposit") or
        std.mem.eql(u8, name, "vault_v2_withdraw") or
        std.mem.eql(u8, name, "pda_storage_process");
}
