// Inline ZigBackend tests moved with the split codegen package.
const common = @import("common.zig");
const std = common.std;
const lir = common.lir;
const match_compiler = common.match_compiler;
const emitConstArrayAddressWorkaround = common.emitConstArrayAddressWorkaround;
const driver = @import("driver.zig");
const emitModule = driver.emitModule;

test "ZigBackend emits the M0 ABI entrypoint signature" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Constant = .{ .Int = 0 } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "// Generated by omlz; do not edit") != null);
    try std.testing.expect(std.mem.indexOf(
        u8,
        source,
        "omlz_user_entrypoint(arena: *Arena, omlz_runtime_input: [*]u8, omlz_runtime_accounts: []AccountRuntime.AccountView, omlz_runtime_instruction_data: []const u8) u64",
    ) != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "    return @intCast(@as(i64, 0));") != null);
}

test "ZigBackend binds entrypoint instruction_data parameter from runtime bytes" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .params = &.{
            .{ .name = "accounts", .ty = .Int },
            .{ .name = "input", .ty = .String },
        },
        .body = .{ .Let = .{
            .name = "_",
            .value = &.{ .Var = .{ .name = "input" } },
            .body = &.{ .Constant = .{ .Int = 0 } },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "for (omlz_runtime_accounts) |omlz_entry_account| omlz_log_account_view(omlz_entry_account);") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const input = omlz_runtime_instruction_data;") != null);
}

test "ZigBackend documents and emits the BPF const-array stack-copy shim" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Constant = .{ .Int = 0 } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "Zig 0.16 BPF workaround") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "stack slot") != null);

    var shim = std.ArrayList(u8).empty;
    defer shim.deinit(std.testing.allocator);
    try emitConstArrayAddressWorkaround(&shim, std.testing.allocator, "omlz_const_array", "omlz_module_const_array");

    try std.testing.expect(std.mem.indexOf(u8, shim.items, "var omlz_const_array_stack_copy = omlz_module_const_array;") != null);
    try std.testing.expect(std.mem.indexOf(u8, shim.items, "const omlz_const_array = &omlz_const_array_stack_copy;") != null);
}

test "ZigBackend emits let expressions as const declarations inside blocks" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Let = .{
            .name = "x",
            .value = &.{ .Constant = .{ .Int = 1 } },
            .body = &.{ .Var = .{ .name = "x" } },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "return @intCast(blk0: {") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const x = @as(i64, 1);") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "break :blk0 x;") != null);
}

test "ZigBackend emits stack-region let expressions as typed stack locals" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Let = .{
            .name = "x",
            .value = &.{ .Constant = .{ .Int = 1 } },
            .body = &.{ .Var = .{ .name = "x" } },
            .ty = .Int,
            .layout = .{ .region = .Stack, .repr = .Flat },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "var x: i64 = @as(i64, 1);") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "break :blk0 x;") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "arena.allocOneOrTrap(i64)") == null);
}

test "ZigBackend emits arena-region let expressions as arena slots" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Let = .{
            .name = "x",
            .value = &.{ .Constant = .{ .Int = 1 } },
            .body = &.{ .Var = .{ .name = "x" } },
            .ty = .Int,
            .layout = .{ .region = .Arena, .repr = .Flat },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "const x = arena.allocOneOrTrap(i64);") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "x.* = @as(i64, 1);") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "break :blk0 x.*;") != null);
}

test "ZigBackend emits pinned integer arithmetic operations" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Let = .{
            .name = "_",
            .value = &.{ .Prim = .{
                .op = .Mul,
                .args = &.{
                    &.{ .Constant = .{ .Int = std.math.minInt(i64) } },
                    &.{ .Constant = .{ .Int = -1 } },
                },
            } },
            .body = &.{ .Let = .{
                .name = "_",
                .value = &.{ .Prim = .{
                    .op = .Div,
                    .args = &.{ &.{ .Constant = .{ .Int = 1 } }, &.{ .Constant = .{ .Int = 0 } } },
                } },
                .body = &.{ .Prim = .{
                    .op = .Mod,
                    .args = &.{ &.{ .Constant = .{ .Int = 0 } }, &.{ .Constant = .{ .Int = 0 } } },
                } },
            } },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "*% @as(i64, -1)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "prelude.intDiv(@as(i64, 1), @as(i64, 0))") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "prelude.intMod(@as(i64, 0), @as(i64, 0))") != null);
}

test "ZigBackend emits comparison bool ADT values and Zig if-expressions" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .If = .{
            .cond = &.{ .Prim = .{
                .op = .Le,
                .args = &.{ &.{ .Constant = .{ .Int = 2 } }, &.{ .Constant = .{ .Int = 3 } } },
            } },
            .then_branch = &.{ .Constant = .{ .Int = 1 } },
            .else_branch = &.{ .Constant = .{ .Int = 0 } },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "if (prelude.Bool.toNative(") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "prelude.Bool.fromNative((@as(i64, 2) <= @as(i64, 3)))") != null);
}

test "ZigBackend emits option constructors through prelude tagged unions" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Let = .{
            .name = "_",
            .value = &.{ .Ctor = .{
                .name = "Some",
                .args = &.{&.{ .Constant = .{ .Int = 1 } }},
                .ty = .{ .Adt = .{ .name = "option", .params = &.{.Int} } },
                .layout = @import("../../core/layout.zig").ctor(1),
            } },
            .body = &.{ .Constant = .{ .Int = 0 } },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "const prelude = @import(\"runtime/prelude.zig\");") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "prelude.Option(i64)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".some = @as(i64, 1)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "arena.allocOneOrTrap(prelude.Option(i64))") != null);
}

test "ZigBackend emits Syscall module calls through runtime bindings" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Let = .{
            .name = "_",
            .value = &.{ .App = .{
                .callee = &.{ .Var = .{ .name = "Syscall.sol_log" } },
                .args = &.{&.{ .Constant = .{ .String = "hello" } }},
                .ty = .Unit,
            } },
            .body = &.{ .Let = .{
                .name = "_",
                .value = &.{ .App = .{
                    .callee = &.{ .Var = .{ .name = "Syscall.sol_log_64" } },
                    .args = &.{
                        &.{ .Constant = .{ .Int = 1 } },
                        &.{ .Constant = .{ .Int = 2 } },
                        &.{ .Constant = .{ .Int = 3 } },
                        &.{ .Constant = .{ .Int = 4 } },
                        &.{ .Constant = .{ .Int = 5 } },
                    },
                    .ty = .Unit,
                } },
                .body = &.{ .App = .{
                    .callee = &.{ .Var = .{ .name = "Syscall.sol_remaining_compute_units" } },
                    .args = &.{&.{ .Ctor = .{
                        .name = "()",
                        .args = &.{},
                        .ty = .Unit,
                        .layout = @import("../../core/layout.zig").unitValue(),
                    } }},
                    .ty = .Int,
                } },
            } },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "const syscalls = @import(\"runtime/syscalls.zig\");") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const cpi = @import(\"runtime/cpi.zig\");") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "var omlz_syscall_bytes_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "[0] = 104") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "[4] = 111") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "syscalls.sol_log_(omlz_syscall_bytes_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "syscalls.sol_log_64_(@as(i64, 1), @as(i64, 2), @as(i64, 3), @as(i64, 4), @as(i64, 5))") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "@as(i64, @intCast(syscalls.sol_remaining_compute_units()))") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_user_Syscall_sol_log") == null);
}

test "ZigBackend emits external calls as direct Zig symbol references" {
    const unit_ty: lir.LTy = .Unit;
    const int_ty: lir.LTy = .Int;
    const module: lir.LModule = .{
        .externals = &.{
            .{
                .name = "sol_log",
                .symbol = "sol_log_",
                .ty = .{ .Closure = .{ .params = &.{.String}, .ret = &unit_ty } },
            },
            .{
                .name = "remaining",
                .symbol = "sol_remaining_compute_units",
                .ty = .{ .Closure = .{ .params = &.{.Unit}, .ret = &int_ty } },
            },
        },
        .entrypoint = .{
            .name = "entrypoint",
            .body = .{ .Let = .{
                .name = "_",
                .value = &.{ .App = .{
                    .callee = &.{ .Var = .{ .name = "sol_log" } },
                    .args = &.{&.{ .Constant = .{ .String = "hi" } }},
                    .ty = .Unit,
                } },
                .body = &.{ .App = .{
                    .callee = &.{ .Var = .{ .name = "remaining" } },
                    .args = &.{&.{ .Ctor = .{
                        .name = "()",
                        .args = &.{},
                        .ty = .Unit,
                        .layout = @import("../../core/layout.zig").unitValue(),
                    } }},
                    .ty = .Int,
                } },
            } },
        },
    };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "syscalls.sol_log_(omlz_syscall_bytes_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "@as(i64, @intCast(syscalls.sol_remaining_compute_units()))") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_user_sol_log") == null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_user_remaining") == null);
}

test "ZigBackend emits Crypto wrappers through arena-backed hash syscalls" {
    const bytes_ty: lir.LTy = .String;
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Let = .{
            .name = "sha",
            .value = &.{ .App = .{
                .callee = &.{ .Var = .{ .name = "Crypto.sha256" } },
                .args = &.{&.{ .Var = .{ .name = "input" } }},
                .ty = bytes_ty,
            } },
            .body = &.{ .App = .{
                .callee = &.{ .Var = .{ .name = "Crypto.keccak256" } },
                .args = &.{&.{ .Var = .{ .name = "sha" } }},
                .ty = bytes_ty,
            } },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "syscalls.sol_sha256_alloc(arena, input)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "syscalls.sol_keccak256_alloc(arena, sha)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_user_Crypto_sha256") == null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_user_Crypto_keccak256") == null);
}

test "ZigBackend slices fixed-array bytes returned by external calls" {
    const unit_ty: lir.LTy = .Unit;
    const bytes_ty: lir.LTy = .String;
    const module: lir.LModule = .{
        .externals = &.{
            .{
                .name = "sol_sha256",
                .symbol = "sol_sha256",
                .ty = .{ .Closure = .{ .params = &.{.String}, .ret = &bytes_ty } },
            },
            .{
                .name = "sol_log",
                .symbol = "sol_log_",
                .ty = .{ .Closure = .{ .params = &.{.String}, .ret = &unit_ty } },
            },
        },
        .entrypoint = .{
            .name = "entrypoint",
            .params = &.{.{ .name = "input", .ty = .String }},
            .body = .{ .Let = .{
                .name = "digest",
                .value = &.{ .App = .{
                    .callee = &.{ .Var = .{ .name = "sol_sha256" } },
                    .args = &.{&.{ .Var = .{ .name = "input" } }},
                    .ty = .String,
                } },
                .body = &.{ .Let = .{
                    .name = "_",
                    .value = &.{ .App = .{
                        .callee = &.{ .Var = .{ .name = "sol_log" } },
                        .args = &.{&.{ .Var = .{ .name = "digest" } }},
                        .ty = .Unit,
                    } },
                    .body = &.{ .Constant = .{ .Int = 0 } },
                } },
            } },
        },
    };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    const hoist_index = std.mem.indexOf(u8, source, "    var omlz_external_bytes_") orelse return error.TestUnexpectedResult;
    const return_index = std.mem.indexOf(u8, source, "    return @intCast(") orelse return error.TestUnexpectedResult;
    try std.testing.expect(hoist_index < return_index);
    try std.testing.expect(std.mem.indexOf(u8, source, ": [32]u8 = undefined;\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const omlz_external_bytes_") == null);
    try std.testing.expect(std.mem.indexOf(u8, source, " = syscalls.sol_sha256(input);") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "syscalls.sol_sha256(input)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "[0..];") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "syscalls.sol_log_(digest)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_user_sol_sha256") == null);
}

test "ZigBackend emits counter byte writes from arena without discarding arena" {
    const module: lir.LModule = .{
        .functions = &.{.{
            .name = "make_bytes",
            .params = &.{.{ .name = "value", .ty = .Int }},
            .return_ty = .String,
            .body = .{ .App = .{
                .callee = &.{ .Var = .{ .name = "write_u64_le" } },
                .args = &.{&.{ .Var = .{ .name = "value" } }},
                .ty = .String,
            } },
        }},
        .entrypoint = .{
            .name = "entrypoint",
            .body = .{ .Constant = .{ .Int = 0 } },
        },
    };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    const func_start = std.mem.indexOf(u8, source, "fn omlz_user_make_bytes") orelse return error.TestUnexpectedResult;
    const func_tail = source[func_start..];
    const entry_start = std.mem.indexOf(u8, func_tail, "\n// source span: unavailable (M0 frontend bridge does not emit spans yet)\npub inline fn") orelse func_tail.len;
    const func_source = func_tail[0..entry_start];

    try std.testing.expect(std.mem.indexOf(u8, func_source, "_ = arena;") == null);
    try std.testing.expect(std.mem.indexOf(u8, func_source, "var omlz_counter_out_") != null);
    try std.testing.expect(std.mem.indexOf(u8, func_source, ": []u8 = undefined;") != null);
    try std.testing.expect(std.mem.indexOf(u8, func_source, "arena.allocIntoOrTrap(u8, 8, &omlz_counter_out_") != null);
    try std.testing.expect(std.mem.indexOf(u8, func_source, "[0..];") == null);
}

test "ZigBackend emits CPI return-data calls through runtime bindings" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Let = .{
            .name = "_",
            .value = &.{ .App = .{
                .callee = &.{ .Var = .{ .name = "Cpi.set_return_data" } },
                .args = &.{&.{ .Constant = .{ .String = "ok" } }},
                .ty = .Unit,
            } },
            .body = &.{ .App = .{
                .callee = &.{ .Var = .{ .name = "Cpi.get_return_data" } },
                .args = &.{&.{ .Ctor = .{
                    .name = "()",
                    .args = &.{},
                    .ty = .Unit,
                    .layout = @import("../../core/layout.zig").unitValue(),
                } }},
                .ty = .String,
            } },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "const cpi = @import(\"runtime/cpi.zig\");") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "cpi.sol_set_return_data(omlz_syscall_bytes_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "cpi.sol_get_return_data_alloc(arena)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "    _ = arena;\n") == null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_user_Cpi_set_return_data") == null);
}

test "ZigBackend emits top-level return-data calls through runtime bindings" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Let = .{
            .name = "_",
            .value = &.{ .App = .{
                .callee = &.{ .Var = .{ .name = "set_return_data" } },
                .args = &.{&.{ .Constant = .{ .String = "ok" } }},
                .ty = .Unit,
            } },
            .body = &.{ .App = .{
                .callee = &.{ .Var = .{ .name = "get_return_data" } },
                .args = &.{&.{ .Ctor = .{
                    .name = "()",
                    .args = &.{},
                    .ty = .Unit,
                    .layout = @import("../../core/layout.zig").unitValue(),
                } }},
                .ty = .String,
            } },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "cpi.sol_set_return_data(omlz_syscall_bytes_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "cpi.sol_get_return_data_alloc(arena)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "    _ = arena;\n") == null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_user_set_return_data") == null);
}

test "ZigBackend emits SPL Token helper calls through runtime bindings" {
    const meta_ty = lir.LTy{ .Record = .{ .name = "account_meta", .params = &.{} } };
    const meta_array_params = [_]lir.LTy{meta_ty};
    const meta_array_ty = lir.LTy{ .Adt = .{ .name = "array", .params = meta_array_params[0..] } };
    const instruction_ty = lir.LTy{ .Record = .{ .name = "instruction", .params = &.{} } };
    const module: lir.LModule = .{
        .record_type_decls = &.{
            .{
                .name = "account_meta",
                .fields = &.{
                    .{ .name = "pubkey", .ty = .{ .TypeRef = .{ .name = "bytes" } } },
                    .{ .name = "is_writable", .ty = .{ .TypeRef = .{ .name = "bool" } } },
                    .{ .name = "is_signer", .ty = .{ .TypeRef = .{ .name = "bool" } } },
                },
            },
            .{
                .name = "instruction",
                .fields = &.{
                    .{ .name = "program_id", .ty = .{ .TypeRef = .{ .name = "bytes" } } },
                    .{ .name = "accounts", .ty = .{ .TypeRef = .{ .name = "array", .args = &.{.{ .TypeRef = .{ .name = "account_meta" } }} } } },
                    .{ .name = "data", .ty = .{ .TypeRef = .{ .name = "bytes" } } },
                },
            },
        },
        .entrypoint = .{
            .name = "entrypoint",
            .body = .{ .Let = .{
                .name = "_",
                .value = &.{ .App = .{
                    .callee = &.{ .Var = .{ .name = "SplToken.transfer_instruction" } },
                    .args = &.{
                        &.{ .Constant = .{ .String = "source_pubkey_32_bytes___________" } },
                        &.{ .Constant = .{ .String = "dest_pubkey_32_bytes_____________" } },
                        &.{ .Constant = .{ .String = "auth_pubkey_32_bytes_____________" } },
                        &.{ .Constant = .{ .Int = 500 } },
                    },
                    .ty = instruction_ty,
                } },
                .body = &.{ .Let = .{
                    .name = "_",
                    .value = &.{ .App = .{
                        .callee = &.{ .Var = .{ .name = "SplToken.program_id" } },
                        .args = &.{&.{ .Ctor = .{
                            .name = "()",
                            .args = &.{},
                            .ty = .Unit,
                            .layout = @import("../../core/layout.zig").unitValue(),
                        } }},
                        .ty = .String,
                    } },
                    .body = &.{ .Let = .{
                        .name = "_",
                        .value = &.{ .App = .{
                            .callee = &.{ .Var = .{ .name = "SplToken.transfer_data" } },
                            .args = &.{&.{ .Constant = .{ .Int = 1 } }},
                            .ty = .String,
                        } },
                        .body = &.{ .Let = .{
                            .name = "_",
                            .value = &.{ .App = .{
                                .callee = &.{ .Var = .{ .name = "SplToken.transfer_account_metas" } },
                                .args = &.{
                                    &.{ .Constant = .{ .String = "source_pubkey_32_bytes___________" } },
                                    &.{ .Constant = .{ .String = "dest_pubkey_32_bytes_____________" } },
                                    &.{ .Constant = .{ .String = "auth_pubkey_32_bytes_____________" } },
                                },
                                .ty = meta_array_ty,
                            } },
                            .body = &.{ .Constant = .{ .Int = 0 } },
                        } },
                    } },
                } },
            } },
        },
    };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "const spl_token = @import(\"runtime/spl_token.zig\");") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "spl_token.writeProgramId(") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "spl_token.encodeTransferInto(") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "arena.allocIntoOrTrap(omlz_type_account_meta, 3") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".is_writable = prelude.Bool.true, .is_signer = prelude.Bool.false") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".is_writable = prelude.Bool.false, .is_signer = prelude.Bool.true") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_user_SplToken_transfer_data") == null);
}

test "ZigBackend emits AccountView field reads and direct writable-field mutations" {
    const account_ty = lir.LTy{ .Record = .{ .name = "account", .params = &.{} } };
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .params = &.{.{ .name = "acct", .ty = account_ty }},
        .body = .{ .Let = .{
            .name = "_",
            .value = &.{ .AccountFieldSet = .{
                .account_expr = &.{ .Var = .{ .name = "acct" } },
                .field_name = "lamports",
                .value = &.{ .Constant = .{ .Int = 7 } },
            } },
            .body = &.{ .Let = .{
                .name = "_",
                .value = &.{ .AccountFieldSet = .{
                    .account_expr = &.{ .Var = .{ .name = "acct" } },
                    .field_name = "data",
                    .value = &.{ .Constant = .{ .String = "ok" } },
                } },
                .body = &.{ .RecordField = .{
                    .record_expr = &.{ .Var = .{ .name = "acct" } },
                    .field_name = "lamports",
                    .record_ty = account_ty,
                } },
            } },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "const acct = if (omlz_runtime_accounts.len > 0) omlz_runtime_accounts[0] else return 1;") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_account_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".lamports.* = @intCast(@as(i64, 7));") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "@memcpy(omlz_account_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".lamportsValue()") != null);
}

test "ZigBackend rejects non-writable account fields with compile errors" {
    const account_ty = lir.LTy{ .Record = .{ .name = "account", .params = &.{} } };
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .params = &.{.{ .name = "acct", .ty = account_ty }},
        .body = .{ .Let = .{
            .name = "_",
            .value = &.{ .AccountFieldSet = .{
                .account_expr = &.{ .Var = .{ .name = "acct" } },
                .field_name = "key",
                .value = &.{ .Constant = .{ .String = "readonly" } },
            } },
            .body = &.{ .Constant = .{ .Int = 0 } },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "@compileError(\"ZXCAML: account field 'key' is read-only\");") != null);
}

test "ZigBackend emits user ADTs as explicit tag and payload structs" {
    const user_ty = lir.LTy{ .Adt = .{ .name = "t", .params = &.{} } };
    const module: lir.LModule = .{
        .type_decls = &.{.{
            .name = "t",
            .variants = &.{
                .{ .name = "A", .tag = 0 },
                .{ .name = "B", .tag = 1 },
                .{ .name = "C", .tag = 2, .payload_types = &.{.{ .TypeRef = .{ .name = "int" } }} },
            },
        }},
        .entrypoint = .{
            .name = "entrypoint",
            .body = .{ .Match = .{
                .scrutinee = &.{ .Ctor = .{
                    .name = "C",
                    .args = &.{&.{ .Constant = .{ .Int = 42 } }},
                    .ty = user_ty,
                    .layout = @import("../../core/layout.zig").ctor(1),
                    .tag = 2,
                    .type_name = "t",
                } },
                .arms = &.{
                    .{
                        .pattern = .{ .Ctor = .{ .name = "A", .args = &.{}, .tag = 0, .type_name = "t" } },
                        .body = &.{ .Constant = .{ .Int = 0 } },
                    },
                    .{
                        .pattern = .{ .Ctor = .{ .name = "C", .args = &.{.{ .Var = "x" }}, .tag = 2, .type_name = "t" } },
                        .body = &.{ .Var = .{ .name = "x" } },
                    },
                },
            } },
        },
    };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "const Tag = enum(u32) { A = 0, B = 1, C = 2 };") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const Payload = union { C: i64 };") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".tag = .C, .payload = .{ .C = @as(i64, 42) }") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "switch (omlz_match_scrutinee_0.tag)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".payload.C") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const x = omlz_match_payload_") != null);
}

test "ZigBackend parameterizes user ADT TypeVar payloads" {
    const box_bool_ty = lir.LTy{ .Adt = .{ .name = "box", .params = &.{.Bool} } };
    const module: lir.LModule = .{
        .type_decls = &.{.{
            .name = "box",
            .params = &.{"'a"},
            .variants = &.{.{
                .name = "Box",
                .tag = 0,
                .payload_types = &.{.{ .TypeVar = "'a" }},
            }},
        }},
        .entrypoint = .{
            .name = "entrypoint",
            .body = .{ .Ctor = .{
                .name = "Box",
                .args = &.{&.{ .Prim = .{
                    .op = .Eq,
                    .args = &.{ &.{ .Constant = .{ .Int = 1 } }, &.{ .Constant = .{ .Int = 1 } } },
                } }},
                .ty = box_bool_ty,
                .layout = @import("../../core/layout.zig").ctor(1),
                .tag = 0,
                .type_name = "box",
            } },
        },
    };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "fn omlz_type_box(comptime omlz_tparam___a: type) type") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "Box: omlz_tparam___a") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_type_box(prelude.Bool){ .tag = .Box") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "Box: i64") == null);
}

test "ZigBackend emits switch-on-discriminant for constructor matches" {
    const option_ty = lir.LTy{ .Adt = .{ .name = "option", .params = &.{.Int} } };
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Match = .{
            .scrutinee = &.{ .Ctor = .{
                .name = "Some",
                .args = &.{&.{ .Constant = .{ .Int = 1 } }},
                .ty = option_ty,
                .layout = @import("../../core/layout.zig").ctor(1),
            } },
            .arms = &.{
                .{
                    .pattern = .{ .Ctor = .{
                        .name = "Some",
                        .args = &.{.{ .Var = "x" }},
                    } },
                    .body = &.{ .Var = .{ .name = "x" } },
                },
                .{
                    .pattern = .{ .Ctor = .{ .name = "None", .args = &.{} } },
                    .body = &.{ .Constant = .{ .Int = 0 } },
                },
            },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "switch (omlz_match_scrutinee_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".some => |omlz_match_payload_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const x = omlz_match_payload_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".none => {") != null);
}

test "ZigBackend emits nested constructor checks with guard fallthrough" {
    const option_int_ty = lir.LTy{ .Adt = .{ .name = "option", .params = &.{.Int} } };
    const nested_option_ty = lir.LTy{ .Adt = .{ .name = "option", .params = &.{option_int_ty} } };
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Match = .{
            .scrutinee = &.{ .Ctor = .{
                .name = "Some",
                .args = &.{&.{ .Ctor = .{
                    .name = "Some",
                    .args = &.{&.{ .Constant = .{ .Int = 42 } }},
                    .ty = option_int_ty,
                    .layout = @import("../../core/layout.zig").ctor(1),
                } }},
                .ty = nested_option_ty,
                .layout = @import("../../core/layout.zig").ctor(1),
            } },
            .arms = &.{
                .{
                    .pattern = .{ .Ctor = .{
                        .name = "Some",
                        .args = &.{.{ .Ctor = .{
                            .name = "Some",
                            .args = &.{.{ .Var = "v" }},
                        } }},
                    } },
                    .guard = &.{ .Prim = .{
                        .op = .Gt,
                        .args = &.{ &.{ .Var = .{ .name = "v" } }, &.{ .Constant = .{ .Int = 40 } } },
                    } },
                    .body = &.{ .Var = .{ .name = "v" } },
                },
                .{
                    .pattern = .{ .Ctor = .{
                        .name = "Some",
                        .args = &.{.{ .Wildcard = {} }},
                    } },
                    .body = &.{ .Constant = .{ .Int = 1 } },
                },
                .{
                    .pattern = .{ .Ctor = .{ .name = "None", .args = &.{} } },
                    .body = &.{ .Constant = .{ .Int = 0 } },
                },
            },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "switch (omlz_match_scrutinee_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".some => |omlz_match_payload_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "if (prelude.Bool.toNative(prelude.Bool.fromNative((v > @as(i64, 40)))))") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "else => {") != null);
}

test "ZigBackend emits guard fallthrough for no-constructor matches" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Match = .{
            .scrutinee = &.{ .Constant = .{ .Int = 5 } },
            .arms = &.{
                .{
                    .pattern = .{ .Var = "v" },
                    .guard = &.{ .Prim = .{
                        .op = .Gt,
                        .args = &.{ &.{ .Var = .{ .name = "v" } }, &.{ .Constant = .{ .Int = 10 } } },
                    } },
                    .body = &.{ .Constant = .{ .Int = 1 } },
                },
                .{
                    .pattern = .{ .Wildcard = {} },
                    .body = &.{ .Constant = .{ .Int = 2 } },
                },
            },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "const v = omlz_match_scrutinee_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "if (prelude.Bool.toNative(prelude.Bool.fromNative((v > @as(i64, 10)))))") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "break :blk0 @as(i64, 1);") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "break :blk0 @as(i64, 2);") != null);
}

test "ZigBackend emits decision-tree switch for five-constructor user ADTs" {
    const five_ty = lir.LTy{ .Adt = .{ .name = "five", .params = &.{} } };
    const module: lir.LModule = .{
        .type_decls = &.{.{
            .name = "five",
            .variants = &.{
                .{ .name = "A", .tag = 0 },
                .{ .name = "B", .tag = 1 },
                .{ .name = "C", .tag = 2 },
                .{ .name = "D", .tag = 3 },
                .{ .name = "E", .tag = 4 },
            },
        }},
        .entrypoint = .{
            .name = "entrypoint",
            .body = .{ .Match = .{
                .scrutinee = &.{ .Ctor = .{
                    .name = "C",
                    .args = &.{},
                    .ty = five_ty,
                    .layout = @import("../../core/layout.zig").ctor(0),
                    .tag = 2,
                    .type_name = "five",
                } },
                .arms = &.{
                    .{ .pattern = .{ .Ctor = .{ .name = "A", .args = &.{}, .type_name = "five" } }, .body = &.{ .Constant = .{ .Int = 1 } } },
                    .{ .pattern = .{ .Ctor = .{ .name = "B", .args = &.{}, .type_name = "five" } }, .body = &.{ .Constant = .{ .Int = 2 } } },
                    .{ .pattern = .{ .Ctor = .{ .name = "C", .args = &.{}, .type_name = "five" } }, .body = &.{ .Constant = .{ .Int = 3 } } },
                    .{ .pattern = .{ .Ctor = .{ .name = "D", .args = &.{}, .type_name = "five" } }, .body = &.{ .Constant = .{ .Int = 4 } } },
                    .{ .pattern = .{ .Ctor = .{ .name = "E", .args = &.{}, .type_name = "five" } }, .body = &.{ .Constant = .{ .Int = 5 } } },
                },
            } },
        },
    };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "switch (omlz_match_scrutinee_0.tag)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".E => {") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".tag == .") == null);
}

test "ZigBackend emits while loop for tagged self tail calls" {
    const n_var = &lir.LExpr{ .Var = .{ .name = "n" } };
    const acc_var = &lir.LExpr{ .Var = .{ .name = "acc" } };
    const fact_func: lir.LFunc = .{
        .name = "fact_loop",
        .params = &.{
            .{ .name = "n", .ty = .Int },
            .{ .name = "acc", .ty = .Int },
        },
        .return_ty = .Int,
        .body = .{ .If = .{
            .cond = &.{ .Prim = .{ .op = .Eq, .args = &.{ n_var, &.{ .Constant = .{ .Int = 0 } } } } },
            .then_branch = acc_var,
            .else_branch = &.{ .App = .{
                .callee = &.{ .Var = .{ .name = "fact_loop" } },
                .args = &.{
                    &.{ .Prim = .{ .op = .Sub, .args = &.{ n_var, &.{ .Constant = .{ .Int = 1 } } } } },
                    &.{ .Prim = .{ .op = .Mul, .args = &.{ acc_var, n_var } } },
                },
                .ty = .Int,
                .callee_ty = .Int,
                .is_tail_call = true,
            } },
        } },
    };
    const module: lir.LModule = .{
        .functions = &.{fact_func},
        .entrypoint = .{
            .name = "entrypoint",
            .body = .{ .App = .{
                .callee = &.{ .Var = .{ .name = "fact_loop" } },
                .args = &.{ &.{ .Constant = .{ .Int = 5 } }, &.{ .Constant = .{ .Int = 1 } } },
                .ty = .Int,
                .callee_ty = .Int,
            } },
        },
    };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "while (true)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_tco_n = omlz_tco_arg_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "continue;") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "return omlz_user_fact_loop(arena, (omlz_tco_n") == null);
}

test "DecisionTree compileMatrix specializes first-column constructors" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const matrix = &.{
        &.{lir.LPattern{ .Ctor = .{ .name = "A", .args = &.{} } }},
        &.{lir.LPattern{ .Ctor = .{ .name = "B", .args = &.{} } }},
        &.{lir.LPattern{ .Wildcard = {} }},
    };
    const actions = &.{ @as(usize, 0), @as(usize, 1), @as(usize, 2) };

    const tree = try match_compiler.compileMatrix(allocator, matrix, actions);
    try std.testing.expectEqual(@as(usize, 0), tree.Switch.column);
    try std.testing.expectEqual(@as(usize, 2), tree.Switch.cases.len);
    try std.testing.expectEqualStrings("A", tree.Switch.cases[0].constructor);
    try std.testing.expectEqual(@as(usize, 0), tree.Switch.cases[0].tree.Leaf);
    try std.testing.expect(tree.Switch.default != null);
    try std.testing.expectEqual(@as(usize, 2), tree.Switch.default.?.Leaf);
}

test "ZigBackend emits default branch and missing-constructor diagnostics" {
    const five_ty = lir.LTy{ .Adt = .{ .name = "five", .params = &.{} } };
    const type_decls = &[_]lir.LVariantType{.{
        .name = "five",
        .variants = &.{
            .{ .name = "A", .tag = 0 },
            .{ .name = "B", .tag = 1 },
            .{ .name = "C", .tag = 2 },
            .{ .name = "D", .tag = 3 },
            .{ .name = "E", .tag = 4 },
        },
    }};
    const scrutinee = &lir.LExpr{ .Ctor = .{
        .name = "A",
        .args = &.{},
        .ty = five_ty,
        .layout = @import("../../core/layout.zig").ctor(0),
        .tag = 0,
        .type_name = "five",
    } };

    const with_default: lir.LModule = .{ .type_decls = type_decls, .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Match = .{
            .scrutinee = scrutinee,
            .arms = &.{
                .{ .pattern = .{ .Ctor = .{ .name = "A", .args = &.{}, .type_name = "five" } }, .body = &.{ .Constant = .{ .Int = 1 } } },
                .{ .pattern = .{ .Wildcard = {} }, .body = &.{ .Constant = .{ .Int = 0 } } },
            },
        } },
    } };
    const default_source = try emitModule(std.testing.allocator, with_default);
    defer std.testing.allocator.free(default_source);
    try std.testing.expect(std.mem.indexOf(u8, default_source, "else => {") != null);
    try std.testing.expect(std.mem.indexOf(u8, default_source, "missing constructors") == null);

    const incomplete: lir.LModule = .{ .type_decls = type_decls, .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Match = .{
            .scrutinee = scrutinee,
            .arms = &.{
                .{ .pattern = .{ .Ctor = .{ .name = "A", .args = &.{}, .type_name = "five" } }, .body = &.{ .Constant = .{ .Int = 1 } } },
                .{ .pattern = .{ .Ctor = .{ .name = "B", .args = &.{}, .type_name = "five" } }, .body = &.{ .Constant = .{ .Int = 2 } } },
            },
        } },
    } };
    const incomplete_source = try emitModule(std.testing.allocator, incomplete);
    defer std.testing.allocator.free(incomplete_source);
    try std.testing.expect(std.mem.indexOf(u8, incomplete_source, "missing constructors: C, D, E") != null);
}

test "ZigBackend omits unused payload captures in constructor matches" {
    const result_ty = lir.LTy{ .Adt = .{ .name = "result", .params = &.{ .Int, .Int } } };
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Match = .{
            .scrutinee = &.{ .Ctor = .{
                .name = "Ok",
                .args = &.{&.{ .Constant = .{ .Int = 5 } }},
                .ty = result_ty,
                .layout = @import("../../core/layout.zig").ctor(1),
            } },
            .arms = &.{
                .{
                    .pattern = .{ .Ctor = .{
                        .name = "Ok",
                        .args = &.{.{ .Var = "x" }},
                    } },
                    .body = &.{ .Var = .{ .name = "x" } },
                },
                .{
                    .pattern = .{ .Ctor = .{
                        .name = "Error",
                        .args = &.{.{ .Wildcard = {} }},
                    } },
                    .body = &.{ .Constant = .{ .Int = 0 } },
                },
            },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, ".err => |omlz_match_payload_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "|_|") == null);
}

test "ZigBackend emits list constructors and cons pattern bindings" {
    const list_ty = lir.LTy{ .Adt = .{ .name = "list", .params = &.{.Int} } };
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Match = .{
            .scrutinee = &.{ .Ctor = .{
                .name = "::",
                .args = &.{
                    &.{ .Constant = .{ .Int = 6 } },
                    &.{ .Ctor = .{
                        .name = "[]",
                        .args = &.{},
                        .ty = list_ty,
                        .layout = @import("../../core/layout.zig").ctor(0),
                    } },
                },
                .ty = list_ty,
                .layout = @import("../../core/layout.zig").ctor(2),
            } },
            .arms = &.{
                .{
                    .pattern = .{ .Ctor = .{ .name = "[]", .args = &.{} } },
                    .body = &.{ .Constant = .{ .Int = 0 } },
                },
                .{
                    .pattern = .{ .Ctor = .{
                        .name = "::",
                        .args = &.{ .{ .Var = "x" }, .{ .Var = "rest" } },
                    } },
                    .body = &.{ .Var = .{ .name = "x" } },
                },
            },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "prelude.List(i64)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".Nil()") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".ConsFromTailPtr(omlz_list_head_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".tag == .cons") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".head") != null);
}

test "ZigBackend emits tuple and record struct operations" {
    const person_ty = lir.LTy{ .Record = .{ .name = "person", .params = &.{} } };
    const module: lir.LModule = .{
        .record_type_decls = &.{.{
            .name = "person",
            .fields = &.{
                .{ .name = "name", .ty = .{ .TypeRef = .{ .name = "string" } } },
                .{ .name = "age", .ty = .{ .TypeRef = .{ .name = "int" } } },
            },
        }},
        .entrypoint = .{
            .name = "entrypoint",
            .body = .{ .Let = .{
                .name = "tup",
                .value = &.{ .Tuple = .{
                    .items = &.{
                        &.{ .Constant = .{ .Int = 1 } },
                        &.{ .Prim = .{
                            .op = .Eq,
                            .args = &.{ &.{ .Constant = .{ .Int = 1 } }, &.{ .Constant = .{ .Int = 1 } } },
                        } },
                        &.{ .Constant = .{ .Int = 42 } },
                    },
                    .ty = .{ .Tuple = &.{ .Int, .Bool, .Int } },
                } },
                .body = &.{ .Let = .{
                    .name = "rec",
                    .value = &.{ .Record = .{
                        .ty = person_ty,
                        .fields = &.{
                            .{ .name = "name", .value = &.{ .Constant = .{ .String = "alice" } } },
                            .{ .name = "age", .value = &.{ .Constant = .{ .Int = 30 } } },
                        },
                    } },
                    .body = &.{ .Let = .{
                        .name = "rec2",
                        .value = &.{ .RecordUpdate = .{
                            .base_expr = &.{ .Var = .{ .name = "rec" } },
                            .fields = &.{.{ .name = "age", .value = &.{ .Constant = .{ .Int = 31 } } }},
                            .ty = person_ty,
                        } },
                        .body = &.{ .Prim = .{
                            .op = .Add,
                            .args = &.{
                                &.{ .TupleProj = .{ .tuple_expr = &.{ .Var = .{ .name = "tup" } }, .index = 0 } },
                                &.{ .RecordField = .{ .record_expr = &.{ .Var = .{ .name = "rec2" } }, .field_name = "age" } },
                            },
                        } },
                    } },
                } },
            } },
        },
    };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "const omlz_type_person = struct") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".@\"0\" = @as(i64, 1)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".@\"1\" = prelude.Bool.fromNative") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "tup).@\"0\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_type_person{ .name = \"alice\", .age = @as(i64, 30) }") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "rec2).age") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_record_base_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".age = @as(i64, 31)") != null);
}

test "ZigBackend emits direct recursive helper functions" {
    const module: lir.LModule = .{
        .functions = &.{.{
            .name = "fact",
            .params = &.{.{ .name = "n", .ty = .Int }},
            .body = .{ .If = .{
                .cond = &.{ .Prim = .{
                    .op = .Le,
                    .args = &.{ &.{ .Var = .{ .name = "n" } }, &.{ .Constant = .{ .Int = 1 } } },
                } },
                .then_branch = &.{ .Constant = .{ .Int = 1 } },
                .else_branch = &.{ .Prim = .{
                    .op = .Mul,
                    .args = &.{
                        &.{ .Var = .{ .name = "n" } },
                        &.{ .App = .{
                            .callee = &.{ .Var = .{ .name = "fact" } },
                            .args = &.{&.{ .Prim = .{
                                .op = .Sub,
                                .args = &.{ &.{ .Var = .{ .name = "n" } }, &.{ .Constant = .{ .Int = 1 } } },
                            } }},
                        } },
                    },
                } },
            } },
        }},
        .entrypoint = .{
            .name = "entrypoint",
            .body = .{ .App = .{
                .callee = &.{ .Var = .{ .name = "fact" } },
                .args = &.{&.{ .Constant = .{ .Int = 5 } }},
            } },
        },
    };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "fn omlz_user_fact(arena: *Arena, n: i64) i64") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_user_fact(arena, (n -% @as(i64, 1)))") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "return @intCast(omlz_user_fact(arena, @as(i64, 5)));") != null);
}
