//! ZigBackend source emission for arena-threaded Lowered IR modules.
//!
//! RESPONSIBILITIES:
//! - Emit readable Zig source from Lowered IR, never Core IR directly.
//! - Preserve the ABI-mandated `omlz_user_entrypoint` function signature.
//! - Keep M0 generated output syntactically valid and `zig fmt` clean.

const std = @import("std");
const lir = @import("../lower/lir.zig");

/// Source emission errors for the M0 Zig backend.
pub const EmitError = std.mem.Allocator.Error || error{
    NegativeIntegerResultUnsupported,
    UnsupportedCallingConvention,
    UnsupportedExpr,
};

/// Emits a complete `.zig` source file for a lowered module.
pub fn emitModule(allocator: std.mem.Allocator, module: lir.LModule) EmitError![]const u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);

    try append(&out, allocator,
        \\// Generated by omlz; do not edit
        \\// Zig 0.16 BPF workaround: before generated code takes the address of
        \\// any module-scope const array, it must copy that array to a local
        \\// stack slot and take the stack copy's address. Otherwise LLVM may
        \\// place the array at low addresses (0x0/0x20) rejected by Solana.
        \\const Arena = @import("runtime/arena.zig").Arena;
        \\const prelude = @import("runtime/prelude.zig");
        \\
        \\
    );
    for (module.functions) |func| {
        try emitFunction(&out, allocator, func);
        try append(&out, allocator, "\n");
    }
    try emitFunction(&out, allocator, module.entrypoint);

    return out.toOwnedSlice(allocator);
}

fn emitFunction(out: *std.ArrayList(u8), allocator: std.mem.Allocator, func: lir.LFunc) EmitError!void {
    switch (func.calling_convention) {
        .ArenaThreaded => {},
    }

    try append(out, allocator, "// source span: unavailable (M0 frontend bridge does not emit spans yet)\n");
    const is_entrypoint = std.mem.eql(u8, func.name, "entrypoint");
    try append(out, allocator, if (is_entrypoint) "pub fn " else "fn ");
    const function_name = try emittedFunctionName(allocator, func.name);
    defer freeEmittedFunctionName(allocator, func.name, function_name);
    try append(out, allocator, function_name);
    try append(out, allocator, "(arena: *Arena");
    if (is_entrypoint) {
        try append(out, allocator, ", input: [*]const u8) callconv(.c) u64 {\n");
    } else {
        for (func.params) |param| {
            try append(out, allocator, ", ");
            try emitIdentifier(out, allocator, param.name);
            try append(out, allocator, ": ");
            const ty_name = try zigTypeName(allocator, param.ty);
            defer allocator.free(ty_name);
            try append(out, allocator, ty_name);
        }
        try append(out, allocator, ") i64 {\n");
    }
    if (!exprNeedsArena(func.body)) {
        try append(out, allocator, "    _ = arena;\n");
    }
    if (is_entrypoint) try append(out, allocator, "    _ = input;\n");
    try append(out, allocator, if (is_entrypoint) "    return @intCast(" else "    return ");
    var ctx: EmitContext = .{};
    try emitExpr(out, allocator, func.body, 1, &ctx);
    try append(out, allocator, if (is_entrypoint) ");\n" else ";\n");
    try append(out, allocator, "}\n");
}

fn emittedFunctionName(allocator: std.mem.Allocator, source_name: []const u8) EmitError![]const u8 {
    if (std.mem.eql(u8, source_name, "entrypoint")) {
        return "omlz_user_entrypoint";
    }

    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);
    try append(&out, allocator, "omlz_user_");
    for (source_name) |ch| {
        if (std.ascii.isAlphanumeric(ch) or ch == '_') {
            try out.append(allocator, ch);
        } else {
            try out.append(allocator, '_');
        }
    }
    return out.toOwnedSlice(allocator);
}

const EmitContext = struct {
    next_block_id: usize = 0,
};

fn emitExpr(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    expr: lir.LExpr,
    indent_level: usize,
    ctx: *EmitContext,
) EmitError!void {
    switch (expr) {
        .Constant => |constant| switch (constant) {
            .Int => |value| {
                const unsigned = std.math.cast(u64, value) orelse return error.NegativeIntegerResultUnsupported;
                try appendPrint(out, allocator, "{d}", .{unsigned});
            },
            .String => |value| try appendPrint(out, allocator, "\"{f}\"", .{std.zig.fmtString(value)}),
        },
        .Var => |var_ref| try emitIdentifier(out, allocator, var_ref.name),
        .App => |app| try emitAppExpr(out, allocator, app, indent_level, ctx),
        .Let => |let_expr| try emitLetExpr(out, allocator, let_expr, indent_level, ctx),
        .If => |if_expr| try emitIfExpr(out, allocator, if_expr, indent_level, ctx),
        .Prim => |prim| try emitPrimExpr(out, allocator, prim, indent_level, ctx),
        .Ctor => |ctor_expr| try emitCtorExpr(out, allocator, ctor_expr, indent_level, ctx),
        .Match => |match_expr| try emitMatchExpr(out, allocator, match_expr, indent_level, ctx),
    }
}

fn emitAppExpr(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    app: lir.LApp,
    indent_level: usize,
    ctx: *EmitContext,
) EmitError!void {
    switch (app.callee.*) {
        .Var => |callee| {
            const function_name = try emittedFunctionName(allocator, callee.name);
            defer freeEmittedFunctionName(allocator, callee.name, function_name);
            try append(out, allocator, function_name);
        },
        else => return error.UnsupportedExpr,
    }
    try append(out, allocator, "(arena");
    for (app.args) |arg| {
        try append(out, allocator, ", ");
        try emitExpr(out, allocator, arg.*, indent_level, ctx);
    }
    try append(out, allocator, ")");
}

fn freeEmittedFunctionName(allocator: std.mem.Allocator, source_name: []const u8, emitted: []const u8) void {
    if (!std.mem.eql(u8, source_name, "entrypoint")) allocator.free(emitted);
}

fn emitIfExpr(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    if_expr: lir.LIf,
    indent_level: usize,
    ctx: *EmitContext,
) EmitError!void {
    const block_id = ctx.next_block_id;
    ctx.next_block_id += 1;
    try appendPrint(out, allocator, "blk{d}: {{\n", .{block_id});
    try emitIndent(out, allocator, indent_level + 1);
    try append(out, allocator, "if (");
    try emitExpr(out, allocator, if_expr.cond.*, indent_level + 1, ctx);
    try append(out, allocator, ") {\n");
    try emitIndent(out, allocator, indent_level + 2);
    try appendPrint(out, allocator, "break :blk{d} ", .{block_id});
    try emitExpr(out, allocator, if_expr.then_branch.*, indent_level + 2, ctx);
    try append(out, allocator, ";\n");
    try emitIndent(out, allocator, indent_level + 1);
    try append(out, allocator, "} else {\n");
    try emitIndent(out, allocator, indent_level + 2);
    try appendPrint(out, allocator, "break :blk{d} ", .{block_id});
    try emitExpr(out, allocator, if_expr.else_branch.*, indent_level + 2, ctx);
    try append(out, allocator, ";\n");
    try emitIndent(out, allocator, indent_level + 1);
    try append(out, allocator, "}\n");
    try emitIndent(out, allocator, indent_level);
    try append(out, allocator, "}");
}

fn emitPrimExpr(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    prim: lir.LPrim,
    indent_level: usize,
    ctx: *EmitContext,
) EmitError!void {
    if (prim.args.len != 2) return error.UnsupportedExpr;
    switch (prim.op) {
        .Div => {
            try append(out, allocator, "@divTrunc(");
            try emitExpr(out, allocator, prim.args[0].*, indent_level, ctx);
            try append(out, allocator, ", ");
            try emitExpr(out, allocator, prim.args[1].*, indent_level, ctx);
            try append(out, allocator, ")");
        },
        .Mod => {
            try append(out, allocator, "@rem(");
            try emitExpr(out, allocator, prim.args[0].*, indent_level, ctx);
            try append(out, allocator, ", ");
            try emitExpr(out, allocator, prim.args[1].*, indent_level, ctx);
            try append(out, allocator, ")");
        },
        else => {
            try append(out, allocator, "(");
            try emitExpr(out, allocator, prim.args[0].*, indent_level, ctx);
            try appendPrint(out, allocator, " {s} ", .{primOpToken(prim.op)});
            try emitExpr(out, allocator, prim.args[1].*, indent_level, ctx);
            try append(out, allocator, ")");
        },
    }
}

fn emitMatchExpr(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    match_expr: lir.LMatch,
    indent_level: usize,
    ctx: *EmitContext,
) EmitError!void {
    const block_id = ctx.next_block_id;
    ctx.next_block_id += 1;
    const scrutinee_name = try std.fmt.allocPrint(allocator, "omlz_match_scrutinee_{d}", .{block_id});
    defer allocator.free(scrutinee_name);

    try appendPrint(out, allocator, "blk{d}: {{\n", .{block_id});
    try emitIndent(out, allocator, indent_level + 1);
    try appendPrint(out, allocator, "const {s} = ", .{scrutinee_name});
    try emitExpr(out, allocator, match_expr.scrutinee.*, indent_level + 1, ctx);
    try append(out, allocator, ";\n");

    if (!matchHasCtorArm(match_expr)) {
        try emitNonCtorMatch(out, allocator, match_expr, scrutinee_name, block_id, indent_level, ctx);
        try emitIndent(out, allocator, indent_level);
        try append(out, allocator, "}");
        return;
    }

    try emitIndent(out, allocator, indent_level + 1);
    try appendPrint(out, allocator, "switch ({s}) {{\n", .{scrutinee_name});

    var emitted = std.ArrayList([]const u8).empty;
    defer emitted.deinit(allocator);
    var emitted_catch_all = false;
    for (match_expr.arms) |arm| {
        if (emitted_catch_all) break;
        switch (arm.pattern) {
            .Ctor => |ctor_pattern| {
                const variant = try ctorVariantName(ctor_pattern.name);
                if (containsString(emitted.items, variant)) continue;
                try emitted.append(allocator, variant);
                try emitCtorMatchArm(out, allocator, ctor_pattern, arm.body.*, block_id, indent_level + 2, ctx);
            },
            .Wildcard, .Var => {
                try emitCatchAllMatchArm(out, allocator, arm.pattern, arm.body.*, scrutinee_name, block_id, indent_level + 2, ctx);
                emitted_catch_all = true;
            },
        }
    }

    if (!emitted_catch_all and !allKnownVariantsCovered(emitted.items)) {
        try emitIndent(out, allocator, indent_level + 2);
        try append(out, allocator, "else => unreachable,\n");
    }
    try emitIndent(out, allocator, indent_level + 1);
    try append(out, allocator, "}\n");
    try emitIndent(out, allocator, indent_level);
    try append(out, allocator, "}");
}

fn emitNonCtorMatch(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    match_expr: lir.LMatch,
    scrutinee_name: []const u8,
    block_id: usize,
    indent_level: usize,
    ctx: *EmitContext,
) EmitError!void {
    if (match_expr.arms.len == 0) return error.UnsupportedExpr;
    const arm = match_expr.arms[0];
    var scrutinee_used = false;
    switch (arm.pattern) {
        .Wildcard => {},
        .Var => |name| if (!std.mem.eql(u8, name, "_") and exprUsesName(arm.body.*, name)) {
            try emitIndent(out, allocator, indent_level + 1);
            try append(out, allocator, "const ");
            try emitIdentifier(out, allocator, name);
            try appendPrint(out, allocator, " = {s};\n", .{scrutinee_name});
            scrutinee_used = true;
        },
        .Ctor => unreachable,
    }
    if (!scrutinee_used) {
        try emitIndent(out, allocator, indent_level + 1);
        try appendPrint(out, allocator, "_ = {s};\n", .{scrutinee_name});
    }
    try emitIndent(out, allocator, indent_level + 1);
    try appendPrint(out, allocator, "break :blk{d} ", .{block_id});
    try emitExpr(out, allocator, arm.body.*, indent_level + 1, ctx);
    try append(out, allocator, ";\n");
}

fn emitCtorMatchArm(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    ctor_pattern: lir.LCtorPattern,
    body: lir.LExpr,
    block_id: usize,
    indent_level: usize,
    ctx: *EmitContext,
) EmitError!void {
    const variant = try ctorVariantName(ctor_pattern.name);
    try emitIndent(out, allocator, indent_level);
    try appendPrint(out, allocator, ".{s} => ", .{variant});
    if (std.mem.eql(u8, ctor_pattern.name, "::")) {
        if (ctor_pattern.args.len != 2) return error.UnsupportedExpr;
        const bind_block_id = ctx.next_block_id;
        ctx.next_block_id += 1;
        try appendPrint(out, allocator, "|omlz_cons| break :blk{d} blk{d}: {{\n", .{ block_id, bind_block_id });
        try emitConsPatternBinding(out, allocator, ctor_pattern.args[0], "omlz_cons.head", body, indent_level + 1);
        try emitConsPatternBinding(out, allocator, ctor_pattern.args[1], "omlz_cons.tail.*", body, indent_level + 1);
        try emitIndent(out, allocator, indent_level + 1);
        try appendPrint(out, allocator, "break :blk{d} ", .{bind_block_id});
        try emitExpr(out, allocator, body, indent_level + 1, ctx);
        try append(out, allocator, ";\n");
        try emitIndent(out, allocator, indent_level);
        try append(out, allocator, "},\n");
        return;
    }
    if (ctor_pattern.args.len == 1) {
        const arg = ctor_pattern.args[0];
        const capture_name: ?[]const u8 = switch (arg) {
            .Wildcard => null,
            .Var => |name| if (exprUsesName(body, name)) name else null,
            .Ctor => return error.UnsupportedExpr,
        };
        if (capture_name) |name| {
            try append(out, allocator, "|");
            try emitIdentifier(out, allocator, name);
            try append(out, allocator, "| ");
        } else {
            try append(out, allocator, "|_| ");
        }
    } else if (ctor_pattern.args.len > 1) {
        return error.UnsupportedExpr;
    }
    try appendPrint(out, allocator, "break :blk{d} ", .{block_id});
    try emitExpr(out, allocator, body, indent_level, ctx);
    try append(out, allocator, ",\n");
}

fn emitConsPatternBinding(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    pattern: lir.LPattern,
    source_expr: []const u8,
    body: lir.LExpr,
    indent_level: usize,
) EmitError!void {
    switch (pattern) {
        .Wildcard => {},
        .Var => |name| if (!std.mem.eql(u8, name, "_") and exprUsesName(body, name)) {
            try emitIndent(out, allocator, indent_level);
            try append(out, allocator, "const ");
            try emitIdentifier(out, allocator, name);
            try appendPrint(out, allocator, " = {s};\n", .{source_expr});
        },
        .Ctor => return error.UnsupportedExpr,
    }
}

fn emitCatchAllMatchArm(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    pattern: lir.LPattern,
    body: lir.LExpr,
    scrutinee_name: []const u8,
    block_id: usize,
    indent_level: usize,
    ctx: *EmitContext,
) EmitError!void {
    try emitIndent(out, allocator, indent_level);
    try append(out, allocator, "else => ");
    const should_bind = switch (pattern) {
        .Var => |name| !std.mem.eql(u8, name, "_") and exprUsesName(body, name),
        .Wildcard => false,
        .Ctor => return error.UnsupportedExpr,
    };
    if (should_bind) {
        const bind_block_id = ctx.next_block_id;
        ctx.next_block_id += 1;
        const name = switch (pattern) {
            .Var => |value| value,
            else => unreachable,
        };
        try appendPrint(out, allocator, "break :blk{d} blk{d}: {{\n", .{ block_id, bind_block_id });
        try emitIndent(out, allocator, indent_level + 1);
        try append(out, allocator, "const ");
        try emitIdentifier(out, allocator, name);
        try appendPrint(out, allocator, " = {s};\n", .{scrutinee_name});
        try emitIndent(out, allocator, indent_level + 1);
        try appendPrint(out, allocator, "break :blk{d} ", .{bind_block_id});
        try emitExpr(out, allocator, body, indent_level + 1, ctx);
        try append(out, allocator, ";\n");
        try emitIndent(out, allocator, indent_level);
        try append(out, allocator, "},\n");
    } else {
        try appendPrint(out, allocator, "break :blk{d} ", .{block_id});
        try emitExpr(out, allocator, body, indent_level, ctx);
        try append(out, allocator, ",\n");
    }
}

fn emitCtorExpr(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    ctor_expr: lir.LCtor,
    indent_level: usize,
    ctx: *EmitContext,
) EmitError!void {
    const ty_name = try zigTypeName(allocator, ctor_expr.ty);
    defer allocator.free(ty_name);
    const variant = try ctorVariantName(ctor_expr.name);

    if (ctor_expr.args.len == 0) {
        try appendPrint(out, allocator, "{s}.{s}", .{ ty_name, variant });
        return;
    }

    if (std.mem.eql(u8, ctor_expr.name, "::")) {
        try emitConsCtorExpr(out, allocator, ctor_expr, ty_name, indent_level, ctx);
        return;
    }

    if (ctor_expr.args.len != 1) return error.UnsupportedExpr;

    const block_id = ctx.next_block_id;
    ctx.next_block_id += 1;
    try appendPrint(out, allocator, "blk{d}: {{\n", .{block_id});

    try emitIndent(out, allocator, indent_level + 1);
    try appendPrint(out, allocator, "const omlz_ctor_payload_{d} = {s}{{ .{s} = ", .{ block_id, ty_name, variant });
    try emitExpr(out, allocator, ctor_expr.args[0].*, indent_level + 1, ctx);
    try append(out, allocator, " };\n");

    switch (ctor_expr.layout.region) {
        .Arena => {
            try emitIndent(out, allocator, indent_level + 1);
            try appendPrint(out, allocator, "const omlz_ctor_box_{d} = arena.alloc({s}, 1) catch unreachable;\n", .{ block_id, ty_name });
            try emitIndent(out, allocator, indent_level + 1);
            try appendPrint(out, allocator, "omlz_ctor_box_{d}[0] = omlz_ctor_payload_{d};\n", .{ block_id, block_id });
            try emitIndent(out, allocator, indent_level + 1);
            try appendPrint(out, allocator, "break :blk{d} omlz_ctor_box_{d}[0];\n", .{ block_id, block_id });
        },
        .Static, .Stack => {
            try emitIndent(out, allocator, indent_level + 1);
            try appendPrint(out, allocator, "break :blk{d} omlz_ctor_payload_{d};\n", .{ block_id, block_id });
        },
    }

    try emitIndent(out, allocator, indent_level);
    try append(out, allocator, "}");
}

fn emitConsCtorExpr(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    ctor_expr: lir.LCtor,
    ty_name: []const u8,
    indent_level: usize,
    ctx: *EmitContext,
) EmitError!void {
    if (ctor_expr.args.len != 2) return error.UnsupportedExpr;

    const block_id = ctx.next_block_id;
    ctx.next_block_id += 1;
    try appendPrint(out, allocator, "blk{d}: {{\n", .{block_id});

    try emitIndent(out, allocator, indent_level + 1);
    try appendPrint(out, allocator, "const omlz_list_head_{d} = ", .{block_id});
    try emitExpr(out, allocator, ctor_expr.args[0].*, indent_level + 1, ctx);
    try append(out, allocator, ";\n");

    try emitIndent(out, allocator, indent_level + 1);
    try appendPrint(out, allocator, "const omlz_list_tail_{d} = ", .{block_id});
    try emitExpr(out, allocator, ctor_expr.args[1].*, indent_level + 1, ctx);
    try append(out, allocator, ";\n");

    try emitIndent(out, allocator, indent_level + 1);
    try appendPrint(out, allocator, "const omlz_list_tail_box_{d} = {s}.Box(arena, omlz_list_tail_{d});\n", .{ block_id, ty_name, block_id });

    try emitIndent(out, allocator, indent_level + 1);
    try appendPrint(out, allocator, "const omlz_ctor_payload_{d} = {s}{{ .cons = .{{ .head = omlz_list_head_{d}, .tail = omlz_list_tail_box_{d} }} }};\n", .{ block_id, ty_name, block_id, block_id });

    switch (ctor_expr.layout.region) {
        .Arena => {
            try emitIndent(out, allocator, indent_level + 1);
            try appendPrint(out, allocator, "const omlz_ctor_box_{d} = arena.alloc({s}, 1) catch unreachable;\n", .{ block_id, ty_name });
            try emitIndent(out, allocator, indent_level + 1);
            try appendPrint(out, allocator, "omlz_ctor_box_{d}[0] = omlz_ctor_payload_{d};\n", .{ block_id, block_id });
            try emitIndent(out, allocator, indent_level + 1);
            try appendPrint(out, allocator, "break :blk{d} omlz_ctor_box_{d}[0];\n", .{ block_id, block_id });
        },
        .Static, .Stack => {
            try emitIndent(out, allocator, indent_level + 1);
            try appendPrint(out, allocator, "break :blk{d} omlz_ctor_payload_{d};\n", .{ block_id, block_id });
        },
    }

    try emitIndent(out, allocator, indent_level);
    try append(out, allocator, "}");
}

fn emitLetExpr(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    let_expr: lir.LLet,
    indent_level: usize,
    ctx: *EmitContext,
) EmitError!void {
    const block_id = ctx.next_block_id;
    ctx.next_block_id += 1;

    try appendPrint(out, allocator, "blk{d}: {{\n", .{block_id});
    try emitIndent(out, allocator, indent_level + 1);
    const is_discard = std.mem.eql(u8, let_expr.name, "_");
    if (is_discard) {
        try append(out, allocator, "_ = ");
        try emitExpr(out, allocator, let_expr.value.*, indent_level + 1, ctx);
        try append(out, allocator, ";\n");
    } else {
        try append(out, allocator, "const ");
        try emitIdentifier(out, allocator, let_expr.name);
        try append(out, allocator, " = ");
        try emitExpr(out, allocator, let_expr.value.*, indent_level + 1, ctx);
        try append(out, allocator, ";\n");
    }
    if (!is_discard and !exprUsesName(let_expr.body.*, let_expr.name)) {
        try emitIndent(out, allocator, indent_level + 1);
        try append(out, allocator, "_ = ");
        try emitIdentifier(out, allocator, let_expr.name);
        try append(out, allocator, ";\n");
    }
    try emitIndent(out, allocator, indent_level + 1);
    try appendPrint(out, allocator, "break :blk{d} ", .{block_id});
    try emitExpr(out, allocator, let_expr.body.*, indent_level + 1, ctx);
    try append(out, allocator, ";\n");
    try emitIndent(out, allocator, indent_level);
    try append(out, allocator, "}");
}

fn exprUsesName(expr: lir.LExpr, name: []const u8) bool {
    return switch (expr) {
        .Constant => false,
        .Var => |var_ref| std.mem.eql(u8, var_ref.name, name),
        .App => |app| blk: {
            if (exprUsesName(app.callee.*, name)) break :blk true;
            for (app.args) |arg| {
                if (exprUsesName(arg.*, name)) break :blk true;
            }
            break :blk false;
        },
        .Let => |let_expr| exprUsesName(let_expr.value.*, name) or
            (!std.mem.eql(u8, let_expr.name, name) and exprUsesName(let_expr.body.*, name)),
        .If => |if_expr| exprUsesName(if_expr.cond.*, name) or exprUsesName(if_expr.then_branch.*, name) or exprUsesName(if_expr.else_branch.*, name),
        .Prim => |prim| blk: {
            for (prim.args) |arg| {
                if (exprUsesName(arg.*, name)) break :blk true;
            }
            break :blk false;
        },
        .Ctor => |ctor_expr| {
            for (ctor_expr.args) |arg| {
                if (exprUsesName(arg.*, name)) return true;
            }
            return false;
        },
        .Match => |match_expr| {
            if (exprUsesName(match_expr.scrutinee.*, name)) return true;
            for (match_expr.arms) |arm| {
                if (!patternBindsName(arm.pattern, name) and exprUsesName(arm.body.*, name)) return true;
            }
            return false;
        },
    };
}

fn exprNeedsArena(expr: lir.LExpr) bool {
    return switch (expr) {
        .Constant, .Var => false,
        .App => true,
        .Let => |let_expr| exprNeedsArena(let_expr.value.*) or exprNeedsArena(let_expr.body.*),
        .If => |if_expr| exprNeedsArena(if_expr.cond.*) or exprNeedsArena(if_expr.then_branch.*) or exprNeedsArena(if_expr.else_branch.*),
        .Prim => |prim| blk: {
            for (prim.args) |arg| {
                if (exprNeedsArena(arg.*)) break :blk true;
            }
            break :blk false;
        },
        .Match => |match_expr| blk: {
            if (exprNeedsArena(match_expr.scrutinee.*)) break :blk true;
            for (match_expr.arms) |arm| {
                if (exprNeedsArena(arm.body.*)) break :blk true;
            }
            break :blk false;
        },
        .Ctor => |ctor_expr| ctor_expr.layout.region == .Arena or blk: {
            for (ctor_expr.args) |arg| {
                if (exprNeedsArena(arg.*)) break :blk true;
            }
            break :blk false;
        },
    };
}

fn patternBindsName(pattern: lir.LPattern, name: []const u8) bool {
    return switch (pattern) {
        .Wildcard => false,
        .Var => |var_name| std.mem.eql(u8, var_name, name),
        .Ctor => |ctor_pattern| {
            for (ctor_pattern.args) |arg| {
                if (patternBindsName(arg, name)) return true;
            }
            return false;
        },
    };
}

fn matchHasCtorArm(match_expr: lir.LMatch) bool {
    for (match_expr.arms) |arm| {
        switch (arm.pattern) {
            .Ctor => return true,
            .Wildcard, .Var => {},
        }
    }
    return false;
}

fn containsString(haystack: []const []const u8, needle: []const u8) bool {
    for (haystack) |value| {
        if (std.mem.eql(u8, value, needle)) return true;
    }
    return false;
}

fn allKnownVariantsCovered(variants: []const []const u8) bool {
    return (containsString(variants, "some") and containsString(variants, "none")) or
        (containsString(variants, "ok") and containsString(variants, "err")) or
        (containsString(variants, "nil") and containsString(variants, "cons"));
}

fn zigTypeName(allocator: std.mem.Allocator, ty: lir.LTy) EmitError![]const u8 {
    return switch (ty) {
        .Int => allocator.dupe(u8, "i64"),
        .Bool => allocator.dupe(u8, "bool"),
        .Unit => allocator.dupe(u8, "void"),
        .String => allocator.dupe(u8, "[]const u8"),
        .Adt => |adt| blk: {
            if (std.mem.eql(u8, adt.name, "option")) {
                if (adt.params.len != 1) return error.UnsupportedExpr;
                const inner = try zigTypeName(allocator, adt.params[0]);
                defer allocator.free(inner);
                break :blk try std.fmt.allocPrint(allocator, "prelude.Option({s})", .{inner});
            }
            if (std.mem.eql(u8, adt.name, "result")) {
                if (adt.params.len != 2) return error.UnsupportedExpr;
                const ok_ty = try zigTypeName(allocator, adt.params[0]);
                defer allocator.free(ok_ty);
                const err_ty = try zigTypeName(allocator, adt.params[1]);
                defer allocator.free(err_ty);
                break :blk try std.fmt.allocPrint(allocator, "prelude.Result({s}, {s})", .{ ok_ty, err_ty });
            }
            if (std.mem.eql(u8, adt.name, "list")) {
                if (adt.params.len != 1) return error.UnsupportedExpr;
                const inner = try zigTypeName(allocator, adt.params[0]);
                defer allocator.free(inner);
                break :blk try std.fmt.allocPrint(allocator, "prelude.List({s})", .{inner});
            }
            return error.UnsupportedExpr;
        },
    };
}

fn primOpToken(op: lir.LPrimOp) []const u8 {
    return switch (op) {
        .Add => "+%",
        .Sub => "-%",
        .Mul => "*%",
        .Eq => "==",
        .Ne => "!=",
        .Lt => "<",
        .Le => "<=",
        .Gt => ">",
        .Ge => ">=",
        .Div, .Mod => unreachable,
    };
}

fn ctorVariantName(name: []const u8) EmitError![]const u8 {
    if (std.mem.eql(u8, name, "None")) return "none";
    if (std.mem.eql(u8, name, "Some")) return "some";
    if (std.mem.eql(u8, name, "Ok")) return "ok";
    if (std.mem.eql(u8, name, "Error")) return "err";
    if (std.mem.eql(u8, name, "[]")) return "nil";
    if (std.mem.eql(u8, name, "::")) return "cons";
    return error.UnsupportedExpr;
}

fn emitIdentifier(out: *std.ArrayList(u8), allocator: std.mem.Allocator, source_name: []const u8) EmitError!void {
    if (source_name.len == 0) {
        try append(out, allocator, "omlz_empty");
        return;
    }

    if (std.ascii.isAlphabetic(source_name[0]) or source_name[0] == '_') {
        for (source_name) |ch| {
            if (std.ascii.isAlphanumeric(ch) or ch == '_') {
                try out.append(allocator, ch);
            } else {
                try out.append(allocator, '_');
            }
        }
    } else {
        try append(out, allocator, "omlz_");
        for (source_name) |ch| {
            if (std.ascii.isAlphanumeric(ch) or ch == '_') {
                try out.append(allocator, ch);
            } else {
                try out.append(allocator, '_');
            }
        }
    }
}

fn emitIndent(out: *std.ArrayList(u8), allocator: std.mem.Allocator, indent_level: usize) EmitError!void {
    var index: usize = 0;
    while (index < indent_level) : (index += 1) {
        try append(out, allocator, "    ");
    }
}

fn emitConstArrayAddressWorkaround(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    local_name: []const u8,
    module_const_name: []const u8,
) EmitError!void {
    // Zig 0.16 BPF quirk: module-scope const arrays can be lowered to low
    // verifier-rejected addresses; every future array address-of site must go
    // through this local stack copy pattern before taking `&`.
    try append(out, allocator, "    var ");
    try append(out, allocator, local_name);
    try append(out, allocator, "_stack_copy = ");
    try append(out, allocator, module_const_name);
    try append(out, allocator, ";\n");
    try append(out, allocator, "    const ");
    try append(out, allocator, local_name);
    try append(out, allocator, " = &");
    try append(out, allocator, local_name);
    try append(out, allocator, "_stack_copy;\n");
}

fn append(out: *std.ArrayList(u8), allocator: std.mem.Allocator, bytes: []const u8) !void {
    try out.appendSlice(allocator, bytes);
}

fn appendPrint(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    comptime fmt: []const u8,
    args: anytype,
) !void {
    const bytes = try std.fmt.allocPrint(allocator, fmt, args);
    defer allocator.free(bytes);
    try append(out, allocator, bytes);
}

test "ZigBackend emits the M0 ABI entrypoint signature" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Constant = .{ .Int = 0 } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "// Generated by omlz; do not edit") != null);
    try std.testing.expect(std.mem.indexOf(
        u8,
        source,
        "omlz_user_entrypoint(arena: *Arena, input: [*]const u8) callconv(.c) u64",
    ) != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "    return @intCast(0);") != null);
}

test "ZigBackend documents and emits the BPF const-array stack-copy shim" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Constant = .{ .Int = 0 } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "Zig 0.16 BPF workaround") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "stack slot") != null);

    var shim = std.ArrayList(u8).empty;
    defer shim.deinit(std.testing.allocator);
    try emitConstArrayAddressWorkaround(&shim, std.testing.allocator, "omlz_const_array", "omlz_module_const_array");

    try std.testing.expect(std.mem.indexOf(u8, shim.items, "var omlz_const_array_stack_copy = omlz_module_const_array;") != null);
    try std.testing.expect(std.mem.indexOf(u8, shim.items, "const omlz_const_array = &omlz_const_array_stack_copy;") != null);
}

test "ZigBackend emits let expressions as const declarations inside blocks" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Let = .{
            .name = "x",
            .value = &.{ .Constant = .{ .Int = 1 } },
            .body = &.{ .Var = .{ .name = "x" } },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "return @intCast(blk0: {") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const x = 1;") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "break :blk0 x;") != null);
}

test "ZigBackend emits option constructors through prelude tagged unions" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Let = .{
            .name = "_",
            .value = &.{ .Ctor = .{
                .name = "Some",
                .args = &.{&.{ .Constant = .{ .Int = 1 } }},
                .ty = .{ .Adt = .{ .name = "option", .params = &.{.Int} } },
                .layout = @import("../core/layout.zig").ctor(1),
            } },
            .body = &.{ .Constant = .{ .Int = 0 } },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "const prelude = @import(\"runtime/prelude.zig\");") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "prelude.Option(i64)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".some = 1") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "arena.alloc(prelude.Option(i64), 1) catch unreachable") != null);
}

test "ZigBackend emits switch-on-discriminant for constructor matches" {
    const option_ty = lir.LTy{ .Adt = .{ .name = "option", .params = &.{.Int} } };
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Match = .{
            .scrutinee = &.{ .Ctor = .{
                .name = "Some",
                .args = &.{&.{ .Constant = .{ .Int = 1 } }},
                .ty = option_ty,
                .layout = @import("../core/layout.zig").ctor(1),
            } },
            .arms = &.{
                .{
                    .pattern = .{ .Ctor = .{
                        .name = "Some",
                        .args = &.{.{ .Var = "x" }},
                    } },
                    .body = &.{ .Var = .{ .name = "x" } },
                },
                .{
                    .pattern = .{ .Ctor = .{ .name = "None", .args = &.{} } },
                    .body = &.{ .Constant = .{ .Int = 0 } },
                },
            },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "switch (omlz_match_scrutinee_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".some => |x| break") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".none => break") != null);
}

test "ZigBackend emits list constructors and cons pattern bindings" {
    const list_ty = lir.LTy{ .Adt = .{ .name = "list", .params = &.{.Int} } };
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Match = .{
            .scrutinee = &.{ .Ctor = .{
                .name = "::",
                .args = &.{
                    &.{ .Constant = .{ .Int = 6 } },
                    &.{ .Ctor = .{
                        .name = "[]",
                        .args = &.{},
                        .ty = list_ty,
                        .layout = @import("../core/layout.zig").ctor(0),
                    } },
                },
                .ty = list_ty,
                .layout = @import("../core/layout.zig").ctor(2),
            } },
            .arms = &.{
                .{
                    .pattern = .{ .Ctor = .{ .name = "[]", .args = &.{} } },
                    .body = &.{ .Constant = .{ .Int = 0 } },
                },
                .{
                    .pattern = .{ .Ctor = .{
                        .name = "::",
                        .args = &.{ .{ .Var = "x" }, .{ .Var = "rest" } },
                    } },
                    .body = &.{ .Var = .{ .name = "x" } },
                },
            },
        } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "prelude.List(i64)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".nil") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".cons = .{ .head = omlz_list_head_") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".cons => |omlz_cons|") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const x = omlz_cons.head;") != null);
}

test "ZigBackend emits direct recursive helper functions" {
    const module: lir.LModule = .{
        .functions = &.{.{
            .name = "fact",
            .params = &.{.{ .name = "n", .ty = .Int }},
            .body = .{ .If = .{
                .cond = &.{ .Prim = .{
                    .op = .Le,
                    .args = &.{ &.{ .Var = .{ .name = "n" } }, &.{ .Constant = .{ .Int = 1 } } },
                } },
                .then_branch = &.{ .Constant = .{ .Int = 1 } },
                .else_branch = &.{ .Prim = .{
                    .op = .Mul,
                    .args = &.{
                        &.{ .Var = .{ .name = "n" } },
                        &.{ .App = .{
                            .callee = &.{ .Var = .{ .name = "fact" } },
                            .args = &.{&.{ .Prim = .{
                                .op = .Sub,
                                .args = &.{ &.{ .Var = .{ .name = "n" } }, &.{ .Constant = .{ .Int = 1 } } },
                            } }},
                        } },
                    },
                } },
            } },
        }},
        .entrypoint = .{
            .name = "entrypoint",
            .body = .{ .App = .{
                .callee = &.{ .Var = .{ .name = "fact" } },
                .args = &.{&.{ .Constant = .{ .Int = 5 } }},
            } },
        },
    };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "fn omlz_user_fact(arena: *Arena, n: i64) i64") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "omlz_user_fact(arena, (n -% 1))") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "return @intCast(omlz_user_fact(arena, 5));") != null);
}
