//! ZigBackend source emission for arena-threaded Lowered IR modules.
//!
//! RESPONSIBILITIES:
//! - Emit readable Zig source from Lowered IR, never Core IR directly.
//! - Preserve the ABI-mandated `omlz_user_entrypoint` function signature.
//! - Keep M0 generated output syntactically valid and `zig fmt` clean.

const std = @import("std");
const lir = @import("../lower/lir.zig");

/// Source emission errors for the M0 Zig backend.
pub const EmitError = std.mem.Allocator.Error || error{
    NegativeIntegerResultUnsupported,
    UnsupportedCallingConvention,
    UnsupportedExpr,
};

/// Emits a complete `.zig` source file for a lowered module.
pub fn emitModule(allocator: std.mem.Allocator, module: lir.LModule) EmitError![]const u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);

    try append(&out, allocator,
        \\// Generated by omlz; do not edit
        \\// Zig 0.16 BPF workaround: before generated code takes the address of
        \\// any module-scope const array, it must copy that array to a local
        \\// stack slot and take the stack copy's address. Otherwise LLVM may
        \\// place the array at low addresses (0x0/0x20) rejected by Solana.
        \\const Arena = @import("runtime/arena.zig").Arena;
        \\
        \\
    );
    try emitFunction(&out, allocator, module.entrypoint);

    return out.toOwnedSlice(allocator);
}

fn emitFunction(out: *std.ArrayList(u8), allocator: std.mem.Allocator, func: lir.LFunc) EmitError!void {
    switch (func.calling_convention) {
        .ArenaThreaded => {},
    }

    try append(out, allocator, "// source span: unavailable (M0 frontend bridge does not emit spans yet)\n");
    try append(out, allocator, "pub fn ");
    try append(out, allocator, try emittedFunctionName(allocator, func.name));
    try append(out, allocator, "(arena: *Arena, input: [*]const u8) callconv(.c) u64 {\n");
    try append(out, allocator, "    _ = arena;\n");
    try append(out, allocator, "    _ = input;\n");
    try append(out, allocator, "    return ");
    try emitExpr(out, allocator, func.body);
    try append(out, allocator, ";\n");
    try append(out, allocator, "}\n");
}

fn emittedFunctionName(allocator: std.mem.Allocator, source_name: []const u8) EmitError![]const u8 {
    if (std.mem.eql(u8, source_name, "entrypoint")) {
        return "omlz_user_entrypoint";
    }

    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);
    try append(&out, allocator, "omlz_user_");
    for (source_name) |ch| {
        if (std.ascii.isAlphanumeric(ch) or ch == '_') {
            try out.append(allocator, ch);
        } else {
            try out.append(allocator, '_');
        }
    }
    return out.toOwnedSlice(allocator);
}

fn emitExpr(out: *std.ArrayList(u8), allocator: std.mem.Allocator, expr: lir.LExpr) EmitError!void {
    switch (expr) {
        .Constant => |constant| switch (constant) {
            .Int => |value| {
                const unsigned = std.math.cast(u64, value) orelse return error.NegativeIntegerResultUnsupported;
                try appendPrint(out, allocator, "{d}", .{unsigned});
            },
        },
    }
}

fn emitConstArrayAddressWorkaround(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    local_name: []const u8,
    module_const_name: []const u8,
) EmitError!void {
    // Zig 0.16 BPF quirk: module-scope const arrays can be lowered to low
    // verifier-rejected addresses; every future array address-of site must go
    // through this local stack copy pattern before taking `&`.
    try append(out, allocator, "    var ");
    try append(out, allocator, local_name);
    try append(out, allocator, "_stack_copy = ");
    try append(out, allocator, module_const_name);
    try append(out, allocator, ";\n");
    try append(out, allocator, "    const ");
    try append(out, allocator, local_name);
    try append(out, allocator, " = &");
    try append(out, allocator, local_name);
    try append(out, allocator, "_stack_copy;\n");
}

fn append(out: *std.ArrayList(u8), allocator: std.mem.Allocator, bytes: []const u8) !void {
    try out.appendSlice(allocator, bytes);
}

fn appendPrint(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    comptime fmt: []const u8,
    args: anytype,
) !void {
    const bytes = try std.fmt.allocPrint(allocator, fmt, args);
    defer allocator.free(bytes);
    try append(out, allocator, bytes);
}

test "ZigBackend emits the M0 ABI entrypoint signature" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Constant = .{ .Int = 0 } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "// Generated by omlz; do not edit") != null);
    try std.testing.expect(std.mem.indexOf(
        u8,
        source,
        "omlz_user_entrypoint(arena: *Arena, input: [*]const u8) callconv(.c) u64",
    ) != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "    return 0;") != null);
}

test "ZigBackend documents and emits the BPF const-array stack-copy shim" {
    const module: lir.LModule = .{ .entrypoint = .{
        .name = "entrypoint",
        .body = .{ .Constant = .{ .Int = 0 } },
    } };

    const source = try emitModule(std.testing.allocator, module);
    defer std.testing.allocator.free(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "Zig 0.16 BPF workaround") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "stack slot") != null);

    var shim = std.ArrayList(u8).empty;
    defer shim.deinit(std.testing.allocator);
    try emitConstArrayAddressWorkaround(&shim, std.testing.allocator, "omlz_const_array", "omlz_module_const_array");

    try std.testing.expect(std.mem.indexOf(u8, shim.items, "var omlz_const_array_stack_copy = omlz_module_const_array;") != null);
    try std.testing.expect(std.mem.indexOf(u8, shim.items, "const omlz_const_array = &omlz_const_array_stack_copy;") != null);
}
