#!/usr/bin/env bash
# Purpose: measure the Colosseum demo's ZxCaml greeting program against the
# isolated Anchor reference by source line count, BPF artifact size, and build
# time, then refresh the generated comparison markdown.
# Args: none.
# Expected output: docs/hackathon/anchor-comparison.generated.md is rewritten,
# and the generated-number block in docs/hackathon/anchor-comparison.md is
# refreshed when that human-readable document exists.
# Exit codes: 0 when ZxCaml builds and measurements are written; non-zero if
# required source files are missing or the ZxCaml BPF build fails. Anchor build
# failures fall back to the committed snapshot values documented below.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

ZXCAML_SRC="${REPO_ROOT}/examples/hackathon_greet.ml"
ZXCAML_SO="${REPO_ROOT}/out/hackathon_greet.so"
ANCHOR_DIR="${REPO_ROOT}/scripts/demo/anchor_reference"
ANCHOR_SRC="${ANCHOR_DIR}/programs/hackathon_greet_anchor/src/lib.rs"
GENERATED_DOC="${REPO_ROOT}/docs/hackathon/anchor-comparison.generated.md"
HUMAN_DOC="${REPO_ROOT}/docs/hackathon/anchor-comparison.md"

# Snapshot recorded on this repository/machine when Anchor/cargo build-sbf is
# unavailable. `scripts/demo/compare.sh` still rebuilds ZxCaml and recomputes
# source line counts before falling back to these Anchor artifact values.
SNAPSHOT_ANCHOR_SO_BYTES=183504
SNAPSHOT_ANCHOR_BUILD_SECONDS=18
SNAPSHOT_ANCHOR_STATUS="snapshot: cargo build-sbf was unavailable; last successful Anchor measurement committed by F-HD2"

TMP_DIR=""

cleanup() {
  if [[ -n "${TMP_DIR}" && -d "${TMP_DIR}" ]]; then
    rm -rf "${TMP_DIR}"
  fi
}
trap cleanup EXIT

require_file() {
  local path="$1"
  if [[ ! -f "${path}" ]]; then
    printf 'required file is missing: %s\n' "${path}" >&2
    exit 1
  fi
}

line_count() {
  wc -l < "$1" | tr -d '[:space:]'
}

byte_count() {
  wc -c < "$1" | tr -d '[:space:]'
}

measure_command() {
  local __result_var="$1"
  shift
  local start="${SECONDS}"
  "$@"
  local status=$?
  printf -v "${__result_var}" '%s' "$((SECONDS - start))"
  return "${status}"
}

build_zxcaml() {
  cd "${REPO_ROOT}"
  if command -v opam >/dev/null 2>&1; then
    eval "$(opam env --switch=zxcaml-p1)"
  fi
  "${SCRIPT_DIR}/01_build.sh"
}

prepare_anchor_workspace() {
  TMP_DIR="$(mktemp -d)"
  local work="${TMP_DIR}/anchor_reference"

  mkdir -p "${work}/programs/hackathon_greet_anchor/src"
  cp "${ANCHOR_DIR}/Cargo.toml" "${work}/Cargo.toml"
  cp "${ANCHOR_DIR}/Anchor.toml" "${work}/Anchor.toml"
  cp "${ANCHOR_DIR}/programs/hackathon_greet_anchor/Cargo.toml" \
    "${work}/programs/hackathon_greet_anchor/Cargo.toml"
  cp "${ANCHOR_SRC}" "${work}/programs/hackathon_greet_anchor/src/lib.rs"
}

build_anchor_reference() {
  prepare_anchor_workspace
  local work="${TMP_DIR}/anchor_reference"
  local out_dir="${TMP_DIR}/anchor-deploy"
  mkdir -p "${out_dir}"

  PATH="${HOME}/.cargo/bin:${PATH}" \
    CARGO_TARGET_DIR="${TMP_DIR}/anchor-target" \
    cargo build-sbf \
      --manifest-path "${work}/Cargo.toml" \
      --sbf-out-dir "${out_dir}"

  local so="${out_dir}/hackathon_greet_anchor.so"
  if [[ ! -s "${so}" ]]; then
    printf 'Anchor build completed but artifact is missing: %s\n' "${so}" >&2
    return 1
  fi
  ANCHOR_SO_BYTES="$(byte_count "${so}")"
}

update_human_doc_block() {
  if [[ ! -f "${HUMAN_DOC}" ]]; then
    return 0
  fi

  local block_file
  block_file="$(mktemp)"
  cat > "${block_file}" <<EOF_BLOCK
<!-- comparison-numbers:start -->
| Metric | ZxCaml \`examples/hackathon_greet.ml\` | Anchor reference \`lib.rs\` | Source |
|---|---:|---:|---|
| Source lines (\`wc -l\`) | ${ZXCAML_LINES} | ${ANCHOR_LINES} | Generated by \`scripts/demo/compare.sh\`; see \`docs/hackathon/anchor-comparison.generated.md\`. |
| BPF artifact size (bytes) | ${ZXCAML_SO_BYTES} | ${ANCHOR_SO_BYTES} | Generated by \`scripts/demo/compare.sh\`; see \`docs/hackathon/anchor-comparison.generated.md\`. |
| Build time (seconds) | ${ZXCAML_BUILD_SECONDS} | ${ANCHOR_BUILD_SECONDS} | Wall-clock seconds from this machine; regenerated by \`scripts/demo/compare.sh\`. |

Anchor measurement status: ${ANCHOR_STATUS}.
<!-- comparison-numbers:end -->
EOF_BLOCK

  python3 - "${HUMAN_DOC}" "${block_file}" <<'PY'
from pathlib import Path
import sys

doc = Path(sys.argv[1])
block = Path(sys.argv[2]).read_text()
text = doc.read_text()
start = "<!-- comparison-numbers:start -->"
end = "<!-- comparison-numbers:end -->"

if start not in text or end not in text:
    text = text.rstrip() + "\n\n" + block + "\n"
else:
    before = text[: text.index(start)]
    after = text[text.index(end) + len(end) :]
    text = before + block + after

doc.write_text(text)
PY
  rm -f "${block_file}"
}

main() {
  require_file "${ZXCAML_SRC}"
  require_file "${ANCHOR_SRC}"
  mkdir -p "$(dirname "${GENERATED_DOC}")" "${REPO_ROOT}/out"

  ZXCAML_LINES="$(line_count "${ZXCAML_SRC}")"
  ANCHOR_LINES="$(line_count "${ANCHOR_SRC}")"

  measure_command ZXCAML_BUILD_SECONDS build_zxcaml
  ZXCAML_SO_BYTES="$(byte_count "${ZXCAML_SO}")"

  ANCHOR_SO_BYTES="${SNAPSHOT_ANCHOR_SO_BYTES}"
  ANCHOR_BUILD_SECONDS="${SNAPSHOT_ANCHOR_BUILD_SECONDS}"
  ANCHOR_STATUS="${SNAPSHOT_ANCHOR_STATUS}"
  if command -v cargo >/dev/null 2>&1 && command -v cargo-build-sbf >/dev/null 2>&1; then
    if measure_command ANCHOR_BUILD_SECONDS build_anchor_reference; then
      ANCHOR_STATUS="built: cargo build-sbf succeeded in an isolated temporary copy"
    else
      printf 'warning: Anchor build failed; using snapshot artifact numbers.\n' >&2
    fi
  else
    printf 'warning: cargo or cargo-build-sbf unavailable; using snapshot artifact numbers.\n' >&2
  fi

  cat > "${GENERATED_DOC}" <<EOF_DOC
<!-- Generated by scripts/demo/compare.sh; do not edit by hand. -->
# Anchor Comparison Measurements

Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

Regenerate from the repository root:

\`\`\`sh
./scripts/demo/compare.sh
\`\`\`

| Metric | ZxCaml \`examples/hackathon_greet.ml\` | Anchor reference \`lib.rs\` | Notes |
|---|---:|---:|---|
| Source lines (\`wc -l\`) | ${ZXCAML_LINES} | ${ANCHOR_LINES} | Counts include comments and blank lines for both files. |
| BPF artifact size (bytes) | ${ZXCAML_SO_BYTES} | ${ANCHOR_SO_BYTES} | ZxCaml artifact: \`out/hackathon_greet.so\`; Anchor artifact is measured from a temporary \`cargo build-sbf\` output. |
| Build time (seconds) | ${ZXCAML_BUILD_SECONDS} | ${ANCHOR_BUILD_SECONDS} | Wall-clock seconds measured by Bash \`SECONDS\`; use as a local demo snapshot, not a benchmark. |

Anchor measurement status: ${ANCHOR_STATUS}.

## Inputs

- ZxCaml source: \`${ZXCAML_SRC#${REPO_ROOT}/}\`
- Anchor source: \`${ANCHOR_SRC#${REPO_ROOT}/}\`
- ZxCaml build command: \`scripts/demo/01_build.sh\`
- Anchor build command: \`cargo build-sbf --manifest-path <temp-anchor-copy>/Cargo.toml --sbf-out-dir <temp-output>\`

## Fallback Snapshot

If Anchor or \`cargo build-sbf\` is unavailable, this script keeps the ZxCaml
measurement live and uses the stored Anchor snapshot:

- Anchor BPF artifact size: ${SNAPSHOT_ANCHOR_SO_BYTES} bytes
- Anchor build time: ${SNAPSHOT_ANCHOR_BUILD_SECONDS} seconds

To refresh the snapshot, install Anchor 0.32.1 and Solana CLI 3.1.12+, then run
\`./scripts/demo/compare.sh\` from the repository root.
EOF_DOC

  update_human_doc_block

  printf 'Wrote %s\n' "${GENERATED_DOC#${REPO_ROOT}/}"
  if [[ -f "${HUMAN_DOC}" ]]; then
    printf 'Updated %s\n' "${HUMAN_DOC#${REPO_ROOT}/}"
  fi
}

main "$@"
