[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hackathon_greet_anchor = "5ZUTYaJjGZgzjMaaTyuamVstcsdhzVXJFHRKTi1QA1dB"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
